services:
  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=payment_system'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - '5432'
