services:
  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=payment_system'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d payment_system" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-app:
    build: .
    ports:
      - "8443:8443"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KEYSTORE_PASS=${KEYSTORE_PASS}
      - CSV_PATH=${CSV_PATH}
    depends_on:
      postgres:
        condition: service_healthy
