ALTER TABLE transactions
ADD COLUMN created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
ADD COLUMN modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE users
ADD COLUMN created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
ADD COLUMN modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE merchants
ADD COLUMN created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
ADD COLUMN modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE roles
ADD COLUMN created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
ADD COLUMN modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW();